export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADED = 'PAGE_LOADED';

export const SIMPLE_CLICK = 'SIMPLE_CLICK';

export const SIMPLE_REQUEST = 'SIMPLE_REQUEST';
export const SIMPLE_REQUEST_SUCCESS = 'SIMPLE_REQUEST_SUCCESS';
export const SIMPLE_REQUEST_FAIL = 'SIMPLE_REQUEST_FAIL';